CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    display_order INTEGER NOT NULL
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500) NOT NULL,
    unit_label VARCHAR(50) NOT NULL,
    unit_price DECIMAL(10, 2) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    image_path VARCHAR(255),
    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT chk_products_unit_price_non_negative
        CHECK (unit_price >= 0)
);

CREATE INDEX idx_products_active ON products (active);
CREATE INDEX idx_products_category_id ON products (category_id);
CREATE INDEX idx_categories_display_order ON categories (display_order);

INSERT INTO categories (id, name, display_order) VALUES
    (1, 'Fresh Produce', 10),
    (2, 'Dairy & Eggs', 20),
    (3, 'Bakery', 30),
    (4, 'Pantry', 40),
    (5, 'Drinks', 50),
    (6, 'Household', 60);

INSERT INTO products (category_id, name, description, unit_label, unit_price, active, image_path) VALUES
    (1, 'Bananas', 'Ripe loose bananas for breakfast, smoothies, and lunch boxes.', 'each', 0.35, TRUE, NULL),
    (1, 'Strawberries', 'Sweet seasonal strawberries packed for easy snacking.', '500g', 3.29, TRUE, NULL),
    (1, 'Cherry Tomatoes', 'Bright cherry tomatoes for salads, pasta, and roasting.', '250g', 2.49, TRUE, NULL),
    (1, 'Baby Spinach', 'Washed tender spinach leaves ready for salads or cooking.', '125g', 1.99, TRUE, NULL),
    (2, 'Whole Milk', 'Fresh whole milk from regional dairies.', '1L', 1.49, TRUE, NULL),
    (2, 'Free Range Eggs', 'Medium free range eggs for baking and breakfast.', '10 pack', 3.79, TRUE, NULL),
    (2, 'Greek Yogurt', 'Creamy plain Greek-style yogurt.', '500g', 2.19, TRUE, NULL),
    (3, 'Sourdough Loaf', 'Crusty sourdough bread baked fresh daily.', '750g', 3.99, TRUE, NULL),
    (3, 'Butter Croissants', 'Flaky butter croissants for a quick breakfast.', '4 pack', 4.49, TRUE, NULL),
    (4, 'Penne Pasta', 'Durum wheat penne for quick weekday meals.', '500g', 1.29, TRUE, NULL),
    (4, 'Chopped Tomatoes', 'Italian chopped tomatoes in rich tomato juice.', '400g', 0.99, TRUE, NULL),
    (4, 'Extra Virgin Olive Oil', 'Cold extracted olive oil for cooking and dressings.', '500ml', 6.99, TRUE, NULL),
    (5, 'Sparkling Water', 'Refreshing sparkling mineral water.', '1.5L', 0.89, TRUE, NULL),
    (5, 'Orange Juice', 'Smooth orange juice with no added sugar.', '1L', 2.59, TRUE, NULL),
    (6, 'Kitchen Towels', 'Absorbent kitchen towels for everyday cleaning.', '2 rolls', 2.99, TRUE, NULL),
    (6, 'Archived Dish Soap', 'Discontinued lemon dish soap kept for archive checks.', '500ml', 1.79, FALSE, NULL);
